## Feature Enginnering

** Adding Libraries and Data we want to parse **

In [6]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import string
import re
import emoji # for counting emojis in each post
cleaned_df=pd.read_csv('mental_health_cleaned.csv')
cleaned_df

                                                    text    label   source
0      a question about the third conditional. i was ...      NaN  Murarka
1      the epitome of my life i've recently requested...     ADHD  Murarka
2      what are your favourites offbeat destinations ...      NaN  Murarka
3      synesthesia survey (what colour is each month ...      NaN  Murarka
4      science ama series: i’m phil baran, and i’m he...      NaN  Murarka
...                                                  ...      ...      ...
64979  Anxiety cause faintness when standing up ? As ...  Anxiety   Sarkar
64980  anxiety heart symptom does anyone else have th...  Anxiety   Sarkar
64981  Travel Anxiety Hi all! Long time anxiety suffe...  Anxiety   Sarkar
64982  fomo from things i’m not involved in does anyo...  Anxiety   Sarkar
64983  Getting through the day How do you get  anythi...  Anxiety   Sarkar

[64984 rows x 3 columns]

**Calculating Post Length AND char Count**
then add it as col to the data frame

In [14]:
cleaned_df['Post_length'] = cleaned_df['text'].apply(lambda x: len(str(x).split()))
cleaned_df['Char_count'] = cleaned_df['text'].str.len()
cleaned_df

,text,label,source,Post_length,Char_count,Count_?,Count_!,Count_emoji
0,a question about the third conditional. i was ...,NaN,Murarka,79,457,2,0,0
1,the epitome of my life i've recently requested...,ADHD,Murarka,143,735,0,0,0
2,what are your favourites offbeat destinations ...,NaN,Murarka,460,3085,1,0,0
3,synesthesia survey (what colour is each month ...,NaN,Murarka,195,1164,2,1,0
4,"science ama series: i’m phil baran, and i’m he...",NaN,Murarka,338,2048,0,2,0
...,...,...,...,...,...,...,...,...
64979,Anxiety cause faintness when standing up ? As ...,Anxiety,Sarkar,23,130,3,0,0
64980,anxiety heart symptom does anyone else have th...,Anxiety,Sarkar,61,306,4,0,0
64981,Travel Anxiety Hi all! Long time anxiety suffe...,Anxiety,Sarkar,159,851,2,1,0
64982,fomo from things i’m not involved in does anyo...,Anxiety,Sarkar,172,891,3,0,0
64983,Getting through the day How do you get anythi...,Anxiety,Sarkar,75,400,1,0,0

## Calculation Density of Punctuations and Emojis
there are amount of emojisa and punctuations existed in each post which can highlight a chance of underlying **MENTAL HEALTH ISSUE**

In [15]:
cleaned_df['Count_?'] = cleaned_df['text'].str.count(re.escape('?')).fillna(0).astype(int)# if posts are free of any punctuations return 0
cleaned_df['Count_!'] = cleaned_df['text'].str.count(re.escape('!')).fillna(0).astype(int)
##counting emojis in each post 
cleaned_df['Count_emoji'] = cleaned_df['text'].apply(lambda x: 0 if pd.isna(x) else emoji.emoji_count(str(x)))
cleaned_df

,text,label,source,Post_length,Char_count,Count_?,Count_!,Count_emoji
0,a question about the third conditional. i was ...,NaN,Murarka,79,457,2,0,0
1,the epitome of my life i've recently requested...,ADHD,Murarka,143,735,0,0,0
2,what are your favourites offbeat destinations ...,NaN,Murarka,460,3085,1,0,0
3,synesthesia survey (what colour is each month ...,NaN,Murarka,195,1164,2,1,0
4,"science ama series: i’m phil baran, and i’m he...",NaN,Murarka,338,2048,0,2,0
...,...,...,...,...,...,...,...,...
64979,Anxiety cause faintness when standing up ? As ...,Anxiety,Sarkar,23,130,3,0,0
64980,anxiety heart symptom does anyone else have th...,Anxiety,Sarkar,61,306,4,0,0
64981,Travel Anxiety Hi all! Long time anxiety suffe...,Anxiety,Sarkar,159,851,2,1,0
64982,fomo from things i’m not involved in does anyo...,Anxiety,Sarkar,172,891,3,0,0
64983,Getting through the day How do you get anythi...,Anxiety,Sarkar,75,400,1,0,0

## VADER SCORING
The **VADER LIB** is a great tool that helps us parse the text and findout about compund score. this score is between -1 to 1 which closer to negative side means the text imperssion is negaitve while as it get closer to positive side it shows more satisfaction we can use this score in trainning our model

In [18]:
analyzer = SentimentIntensityAnalyzer() ##intiliazing Analyzer 
cleaned_df['Vader_variable'] = cleaned_df['text'].apply(lambda x: analyzer.polarity_scores(x)['compound']) ## add the col to the data frame
cleaned_df

,text,label,source,Post_length,Char_count,Count_?,Count_!,Count_emoji,Vader_variable
0,a question about the third conditional. i was ...,NaN,Murarka,79,457,2,0,0,0.5799
1,the epitome of my life i've recently requested...,ADHD,Murarka,143,735,0,0,0,0.3875
2,what are your favourites offbeat destinations ...,NaN,Murarka,460,3085,1,0,0,0.9997
3,synesthesia survey (what colour is each month ...,NaN,Murarka,195,1164,2,1,0,0.8904
4,"science ama series: i’m phil baran, and i’m he...",NaN,Murarka,338,2048,0,2,0,0.9922
...,...,...,...,...,...,...,...,...,...
64979,Anxiety cause faintness when standing up ? As ...,Anxiety,Sarkar,23,130,3,0,0,-0.4479
64980,anxiety heart symptom does anyone else have th...,Anxiety,Sarkar,61,306,4,0,0,0.9190
64981,Travel Anxiety Hi all! Long time anxiety suffe...,Anxiety,Sarkar,159,851,2,1,0,-0.9585
64982,fomo from things i’m not involved in does anyo...,Anxiety,Sarkar,172,891,3,0,0,0.9140
64983,Getting through the day How do you get anythi...,Anxiety,Sarkar,75,400,1,0,0,0.6552

## Final Export 
the following calculations will be shared with other teammates to start next part of project which is trainning model to identify mental health issues

In [20]:
cleaned_df.to_csv('mental_health_engineered.csv', index=False)